### ISSUE TITLE
Observaciones de la pantalla de informe de  gastos

### ISSUE THREAD

**Issue by parbizuc** [spsolutionsmexico/GestionGasto#17]
@dulcoral revisar estos issues para la pantalla de Nuevo informe

1. En la cabecera falta el nombre del usuario y el perfil de manera similar a la pantalla de Anticipos
2. El texto del campo titulo debe estar justificado a la izquierda
3. La etiqueta Adelanto Relacionado debe remplazarse por Anticipo Relacionado
4. Los campos Fechas deben levantar el control de seleccion de fecha
5.Al hacer click en cualquier seccion se debe ocultar el teclado
6. Remplazar la etiqueta "Gastos relacionados", por "Seleccionar los gastos relacionados"
7. Al GUARDAR No se registra la información en pantalla.
8. Realizar la validación de datos por campos, de la misma manera que el formulario de anticipos
9. Boton ENVIAR tampoco graba datos.

**Comment by dulcoral** [comment]
4.1(5). No se puede ya que es una vista de tipo scroll.
6 y 8. Es debido a que la pantalla de informes no esta realizada aún.
